### ISSUE TITLE
Returns https instead of http if host is 127.0.0.1

### ISSUE THREAD

**Issue by ttoni** [jakeburden/next-absolute-url#17]
The absoluteUrl function returns only http as protocol if host is 'localhost'. 
In case of '127.0.0.1' it always returns https. 
In some cases we have to use 127.0.0.1 instead of localhost, but that mixes up protocols returned by absoluteUrl.

**Comment by bas080** [comment]
I see this as a bug as it makes little sense to have localhost be http and an equivalent to be https.

**Comment by aceaspades-worldspark** [comment]
I'm running into this exact issue right now. 

Version: 1.2.2

**Comment by aceaspades-worldspark** [comment]
@jakeburden @FDiskas 

It looks like this fix was made in `index.ts` but doesn't seem to have transpiled properly into `index.js`. Sounds silly, but I'm currently running into this exact issue. I checked the code, and it looks like the old version remains in `index.js`
